language: node_js
node_js:
  - 8.12.0

# S: Build Lifecycle
install:
  - npm install

before_script:
# - npm install -g gulp

script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "songxingguo"
  - git config user.email "1328989942@qq.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
  # Add Tag
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m \"Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER\",
  # Github Pages
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" master:master --tags
# E: Build LifeCycle

branches:
  only:
    - master
env:
  global:
    # Github Pages
    - GH_REF: github.com/songxingguo/vue-todoList.git
